# Generated by Django 3.2.25 on 2024-09-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Receipe',
        ),
    ]
