# Generated by Django 3.2.25 on 2024-09-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_recipe_receipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Recipe',
        ),
    ]
